name = "ExplicitFluxDiffJacobians"
uuid = "61bfa2bf-ac51-4dc3-9c62-6a5180432d13"
authors = ["Jesse Chan", "Christina Taylor"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
